import { Head, Link } from '@inertiajs/react';
import { Errors, Form, useShared } from '../components';

export default function Auth({mode}: {mode: 'login' | 'register' | 'verify'}) {
    const {copy: t} = useShared();
    if (mode === 'verify') return <section className="auth-page"><Head title={t.verify}/><img src="/images/logo-black.svg" alt=""/><h1>{t.verify}</h1><p>{t.verify_hint}</p><Errors/><Form action="/email/verification-notification"><button className="button primary">{t.resend}</button></Form><Form action="/logout"><button className="text-button">{t.logout}</button></Form></section>;
    const register = mode === 'register';
    return <section className="auth-page"><Head title={register ? t.register : t.login}/><Link className="auth-brand" href="/"><img src="/images/logo-black.svg" alt=""/>waasabi</Link><h1>{register ? t.register : t.login}</h1><Errors/><Form action={register ? '/register' : '/login'} className="stack"><input className="honeypot" name={register ? 'contact_time' : 'website'} tabIndex={-1} autoComplete="off"/>{register && <label>{t.name}<input name="name" required autoComplete="name"/></label>}<label>{t.email}<input type="email" name="email" required autoComplete="email"/></label><label>{t.password}<input type="password" name="password" required autoComplete={register ? 'new-password' : 'current-password'}/></label>{register && <><label>{t.password_confirmation}<input type="password" name="password_confirmation" required autoComplete="new-password"/></label><label className="check"><input type="checkbox" name="accept_legal" value="1" required/>I accept the <a href="/legal/terms">terms</a> and <a href="/legal/privacy">privacy policy</a>.</label></>} {!register && <label className="check"><input type="checkbox" name="remember" value="1"/>{t.remember}</label>}<button className="button primary">{register ? t.register : t.login}</button></Form>{register ? <p>Already a member? <Link href="/login">{t.login}</Link></p> : <p><Link href="/forgot-password">{t.forgot}</Link> · <Link href="/register">{t.register}</Link></p>}</section>;
}
