import { Head, Link, router } from '@inertiajs/react';
import { ArrowUpRight, Plus, Search } from 'lucide-react';
import { useRef } from 'react';
import { Empty, InfinitePage, PersonLine, date, useShared } from '../components';
import type { Opening, Pagination } from '../types';

export default function Collaborations({openings, roles, availability, formats, filters}: {openings: Pagination<Opening>; roles: Record<string, string>; availability: Record<string, string>; formats: Record<string, string>; filters: Record<string, string>}) {
    const {copy: t, auth} = useShared();
    const searchTimer = useRef<number | undefined>(undefined);
    const apply = (form: HTMLFormElement, delay = 0) => {window.clearTimeout(searchTimer.current); searchTimer.current = window.setTimeout(() => router.get('/collaboration', Object.fromEntries(new FormData(form)), {preserveState: true, preserveScroll: true, replace: true}), delay);};
    return <section className="collaboration-page"><Head title={t.help}/><div className="page-heading"><div><h1>{t.help}</h1><p>{t.new_help_hint}</p></div><Link className="button primary" href="/collaboration/create"><Plus size={17}/>{t.new_help}</Link></div>
        <div className="collaboration-intro"><p><strong>{t.want_to_help}</strong> {t.want_to_help_hint}</p><Link className="text-link" href="/people">{t.available_collaborators} →</Link></div>
        {auth.user && <nav className="collaboration-scopes" aria-label={t.collaboration_scope}>{[['', t.all_requests], ['mine', t.my_requests], ['applied', t.my_replies]].map(([value, label]) => <Link key={value} className={(filters.scope || '') === value ? 'active' : ''} href={`/collaboration?${new URLSearchParams({...filters, scope: value})}`}>{label}</Link>)}</nav>}
        <form className="collaboration-filters" onSubmit={event => event.preventDefault()}><label className="collaboration-search"><Search size={17}/><input name="q" defaultValue={filters.q || ''} placeholder={t.collaboration_search_placeholder} onChange={event => event.currentTarget.form && apply(event.currentTarget.form, 260)}/></label><input type="hidden" name="scope" value={filters.scope || ''}/><label>{t.role}<select name="role" defaultValue={filters.role || ''} onChange={event => event.currentTarget.form && apply(event.currentTarget.form)}><option value="">{t.any_role}</option>{Object.entries(roles).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>{t.commitment}<select name="availability" defaultValue={filters.availability || ''} onChange={event => event.currentTarget.form && apply(event.currentTarget.form)}><option value="">{t.any_availability}</option>{Object.entries(availability).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>{t.format}<select name="format" defaultValue={filters.format || ''} onChange={event => event.currentTarget.form && apply(event.currentTarget.form)}><option value="">{t.any_format}</option>{Object.entries(formats).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></form>
        <div className="search-suggestions" aria-label={t.search_examples}><span>{t.try_searching}</span>{['design', 'code', 'music', 'writing', 'remote', 'quick'].map(term => <Link key={term} href={`/collaboration?q=${encodeURIComponent(term)}`}>{term}</Link>)}</div>
        <InfinitePage data="openings" className="collaboration-list">{openings.data.map(opening => <article className="job-opening" key={opening.id}><div className="job-opening-main"><div className="job-opening-kicker"><span>{roles[opening.role] || opening.role.replace(/-/g, ' ')}</span><span className="meta">{opening.open ? t.open : t.closed} · {date(opening.date)}</span></div><Link href={`/collaboration/${opening.id}`}><h2>{opening.title}</h2></Link><p>{opening.summary}</p>{opening.skills.length > 0 && <div className="job-skills"><small>{t.help_needed}</small>{opening.skills.slice(0, 6).map(skill => <span key={skill}>{skill}</span>)}</div>}<div className="job-opening-facts"><span>{availability[opening.availability] || opening.availability.replace(/-/g, ' ')}</span><span>{formats[opening.format] || opening.format}</span><span>{opening.applications} {t.replies}</span>{opening.project && <span>{opening.project.title}</span>}</div></div><footer><PersonLine person={opening.author}/><Link className="button small" href={`/collaboration/${opening.id}`}>{opening.author.id === auth.user?.id ? t.view_request : t.offer_help}<ArrowUpRight size={15}/></Link></footer></article>)}</InfinitePage>{!openings.data.length && <Empty action={<Link className="button" href="/collaboration/create">{t.new_help}</Link>}>{t.empty}</Empty>}
    </section>;
}
