import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, ExternalLink, Send } from 'lucide-react';
import { Avatar, Errors, Form, PersonLine, date, useShared } from '../components';
import type { Comment, Opening, Person } from '../types';

type PrivateMessage = {id: number; body: string; date: string; author: Person};
type Application = {id: number; status: string; message: string; user: Person; project: {id: number; slug: string; title: string} | null; messages: PrivateMessage[]};

function PrivateThread({application}: {application: Application}) {
    const {copy: t, auth} = useShared();
    const canMessage = ['pending', 'accepted'].includes(application.status);
    if (!canMessage && !application.messages.length) return null;
    return <div className="private-thread"><div className="private-thread-head"><strong>{t.private_thread}</strong><span>{t.private_thread_hint}</span></div><div className="private-messages">{application.messages.map(message => <article className={message.author.id === auth.user?.id ? 'mine' : ''} key={message.id}><PersonLine person={message.author} detail={date(message.date)}/><p>{message.body}</p></article>)}{!application.messages.length && <p className="meta">{t.private_thread_empty}</p>}</div>{canMessage && <Form action={`/collaboration/applications/${application.id}/messages`} reset className="private-message-form"><label className="sr-only" htmlFor={`private-message-${application.id}`}>{t.message_placeholder}</label><textarea id={`private-message-${application.id}`} name="body" required minLength={2} maxLength={2000} rows={1} placeholder={t.message_placeholder}/><button className="comment-send" aria-label={t.send} title={t.send}><Send size={17}/></button></Form>}</div>;
}

export default function Collaboration({opening, isOwner, applications, comments, candidateProjects}: {opening: Opening; isOwner: boolean; applications: Application[]; comments: Comment[]; candidateProjects: {id: number; title: string}[]}) {
    const {copy: t, auth} = useShared();
    const mine = applications.find(application => application.user.id === auth.user?.id);
    const stateTitle = mine?.status === 'accepted' ? t.collaboration_started : mine?.status === 'pending' ? t.response_sent : mine ? (t[mine.status] || mine.status) : '';
    const stateHint = mine?.status === 'accepted' ? t.collaboration_started_hint : mine?.status === 'pending' ? t.response_sent_hint : t.response_inactive_hint;
    return <section className="collaboration-detail"><Head title={opening.title}/><Link className="back-link" href="/collaboration"><ArrowLeft size={16}/>{t.help}</Link><Errors/>
        <header><PersonLine person={opening.author}/><h1>{opening.title}</h1><p className="lead">{opening.summary}</p><div className="opening-facts meta"><span>{opening.role.replace(/-/g, ' ')}</span><span>{opening.availability.replace(/-/g, ' ')}</span><span>{opening.format}</span><span>{opening.open ? t.open : t.closed}</span></div>{opening.project && <Link className="text-link" href={`/projects/${opening.project.slug}`}>{opening.project.title} →</Link>}</header>
        {isOwner ? <section className="applications-section"><div className="section-heading"><h2>{t.applications}</h2><Form action={`/collaboration/${opening.id}/status`} method="patch"><input type="hidden" name="status" value={opening.open ? 'closed' : 'open'}/><button className="button small">{opening.open ? t.close : t.reopen}</button></Form></div>{applications.map(application => <article id={`application-${application.id}`} className="application-card" key={application.id}><header><PersonLine person={application.user}/><span className="state-label">{t[application.status] || application.status}</span></header><p>{application.message}</p>{application.project && <Link className="text-link" href={`/projects/${application.project.slug}`}>{t.bring_project}: {application.project.title} →</Link>}{application.status === 'accepted' && application.user.portfolio_url && <a className="text-link contact-link" href={application.user.portfolio_url} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{t.contact}</a>}{application.status === 'pending' && <div className="button-row"><Form action={`/collaboration/applications/${application.id}`} method="patch"><input type="hidden" name="status" value="accepted"/><button className="button primary small">{t.accept}</button></Form><Form action={`/collaboration/applications/${application.id}`} method="patch"><input type="hidden" name="status" value="rejected"/><button className="button small">{t.decline}</button></Form></div>}<PrivateThread application={application}/></article>)}{!applications.length && <p className="meta">{t.no_applications}</p>}</section>
        : auth.user && opening.open && !mine ? <section className="apply-block"><h2>{t.join}</h2><p>{t.apply_hint}</p><Form action={`/collaboration/${opening.id}/applications`} className="stack"><input type="text" name="website" tabIndex={-1} className="honeypot"/>{candidateProjects.length > 0 && <label>{t.bring_project}<select name="applicant_post_id"><option value="">{t.no_project}</option>{candidateProjects.map(project => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label>}<label>{t.hello}<textarea name="message" rows={3}/></label><button className="button primary">{t.join}</button></Form></section>
        : mine ? <section id={`application-${mine.id}`} className="collaboration-workspace"><div className="workspace-state"><strong>{stateTitle}</strong><p>{stateHint}</p></div><div className="button-row">{mine.status === 'accepted' && opening.author.portfolio_url && <a className="button small" href={opening.author.portfolio_url} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{t.contact}</a>}{mine.status === 'accepted' && opening.project && <Link className="button small" href={`/projects/${opening.project.slug}`}>{t.open_project}</Link>}{['pending', 'accepted'].includes(mine.status) && <Form action={`/collaboration/applications/${mine.id}`} method="delete"><button className="text-button danger">{mine.status === 'accepted' ? t.leave : t.withdraw}</button></Form>}</div><PrivateThread application={mine}/></section> : null}
        <section className="discussion public-discussion"><h2>{t.public_discussion}</h2><p className="meta">{t.public_discussion_hint}</p>{auth.user && <div className="comment-composer"><Avatar person={auth.user}/><Form action={`/collaboration/${opening.id}/comments`} reset className="comment-form"><label className="sr-only" htmlFor="collaboration-comment-body">{t.comment}</label><textarea id="collaboration-comment-body" name="body" required minLength={2} maxLength={2000} rows={3} placeholder={t.comment_placeholder}/><div className="comment-form-actions"><span>{t.comment_hint}</span><button className="comment-send" aria-label={t.send} title={t.send}><Send size={18}/></button></div></Form></div>}{comments.map(comment => <article className="comment" key={comment.id}><PersonLine person={comment.author}/><p>{comment.body}</p></article>)}</section>
    </section>;
}
