import { setupIcons, setupImageFallbacks, setupScribbleAvatars } from '../core/media';
import { toast } from '../core/toast';
import { setupPublishForm } from './publish';
import { setupCommentForms, setupCommentSorts, setupCommentChunks, setupCommentVotes } from './comments';
import { setupReviewForms, setupReviewVotes } from './reviews';
import { setupSpotlightSearch } from './spotlight-search';
import { setupFeedTabs, setupFeedFilters, setupInfiniteFeed, insertFeedQaBlocks, setupQaBlocks } from './feed';
import { setupReadingExperience, updateCardsProgress } from './reading';
import { setupNotificationsMenu, setupNotificationReads, setupNotificationsPage } from '../ui/notifications';
import { setupReadLaterMenu, renderReadLaterList } from '../ui/read-later';
import { setupActionMenus } from '../ui/action-menus';
import { setupSettingsModal } from '../ui/settings-modal';
import { setupProfileSettingsForm, setupProfileSettingsPage } from '../ui/profile-settings';
import { setupShareButtons } from '../ui/share';
import { setupReportModal } from '../ui/report';
import { setupAdminInterface, setupAdminModeToggle, setupAdminControls, setupConfirmActions, setupAuthorActions, setupModerationReasonForms } from '../ui/admin';
import { setupTabs } from '../ui/tabs';
import { setupPostJumpButtons } from '../ui/post-jump';
import { setupNsfwReveal } from '../ui/nsfw';
import { setupActionToggles } from '../ui/action-toggles';
import { setupFollowButtons } from '../ui/follow';
import { setupCarousels } from '../ui/carousels';
import { setupNavFooterOffset } from '../ui/nav-footer';
import { setupProfileBanner } from '../ui/profile-banner';
import { setupProfileBadges } from './profile-badges';
import { setupIconTooltips } from '../ui/tooltips';
import { setupBannedGuard } from '../ui/banned-guard';
import { setupProfileMedia } from './profile-media';
import { setupCookieConsent } from '../ui/cookie-consent';
import { setupScrollTopRail } from '../ui/scroll-top';
import { setupMediaViewer } from '../ui/media-viewer';
import { setupSupportFaq } from './support';
import { clearPublishDraft } from '../core/storage';
import { setupNotFoundGame } from './not-found-game';

export const hydratePage = () => {
    const savedDraft = document.querySelector<HTMLElement>('[data-clear-draft]');
    if (savedDraft?.dataset.clearDraft) {
        clearPublishDraft(savedDraft.dataset.clearDraft);
        delete savedDraft.dataset.clearDraft;
    }
    setupIcons();
    setupImageFallbacks();
    setupScribbleAvatars();
    const toastMessage = document.body.dataset.toastMessage ?? '';
    if (toastMessage) {
        toast.show(toastMessage);
        delete document.body.dataset.toastMessage;
    }
    setupBannedGuard();
    setupCookieConsent();
    setupPublishForm();
    if (document.querySelector('[data-editor]')) {
        void import('./editor').then(({ setupArticleEditor }) => setupArticleEditor());
    }
    setupCommentForms();
    setupCommentVotes();
    setupCommentSorts();
    setupCommentChunks();
    setupReviewForms();
    setupReviewVotes();
    setupNotificationsMenu();
    setupNotificationReads();
    setupNotificationsPage();
    setupReadLaterMenu();
    setupActionMenus();
    setupSettingsModal();
    setupSpotlightSearch();
    setupSupportFaq();
    setupProfileSettingsForm();
    setupProfileSettingsPage();
    setupShareButtons();
    setupReportModal();
    setupProfileBanner();
    setupProfileBadges();
    setupProfileMedia();
    setupAdminInterface();
    setupAdminModeToggle();
    setupAdminControls();
    setupModerationReasonForms();
    setupConfirmActions();
    setupAuthorActions();
    setupTabs();
    setupFeedTabs();
    setupFeedFilters();
    setupInfiniteFeed();
    insertFeedQaBlocks();
    setupQaBlocks();
    setupPostJumpButtons();
    setupNsfwReveal();
    setupActionToggles();
    setupFollowButtons();
    setupReadingExperience();
    setupCarousels();
    setupMediaViewer();
    setupIconTooltips();
    setupNavFooterOffset();
    setupScrollTopRail();
    setupNotFoundGame();
    renderReadLaterList();
    updateCardsProgress();
};
